spring:
  cloud:
    stream:
      bindings:
        input:
          destination: TWEETS.Q.POSITIVE
          binder: localsolace
          group: attendee
        output:
          destination: tweets/stream/nofeatures/noyelling/positive/attendee
          binder: localsolace
      binders:
        local_solace:
          type: solace
          environment:
            solace:
              java:
                host: tcp://localhost:55555
                msgVpn: default
                clientUsername: default
                clientPassword: default
                connectRetries: -1
                reconnectRetries: -1
      solace:
        bindings:
          input:
            consumer:
              queueAdditionalSubscriptions: tweets/stream/nofeatures/noyelling
logging:
  level:
    root: INFO
    com.solacesystems.jcsmp: INFO
    org.springframework: INFO
    
server:
  port: 8091
