spring:
  cloud:
    stream:
      bindings:
        input:
          destination: TWEETS.Q
          binder: local_solace
          group: YELLING
        output:
          destination: T/tweets/stream/noyelling
          binder: local_solace
      binders:
        local_solace:
          type: solace
          environment:
            spring:
              solace:
                host: tcp://localhost:55555
                msgVpn: default
                clientUsername: default
                clientPassword: default
                connectRetries: -1
                reconnectRetries: -1
      solace:
        bindings:
          input:
            consumer:
              queueAdditionalSubscriptions: T/tweets/stream
logging:
  level:
    root: INFO
    com.solacesystems.jcsmp: INFO
    org.springframework: INFO
    
server:
  port: 8092