spring:
  cloud:
    stream:
      bindings:
        input:
          destination: TWEETS
          binder: local_solace
          group: MARKETING
      binders:
        local_solace:
          type: solace
          environment:
            solace:
              java:
                host: tcp://localhost:55555
                msgVpn: default
                clientUsername: default
                clientPassword: default
      solace:
        bindings:
          input:
            consumer:
              queueAdditionalSubscriptions: T/tweets/stream
                
logging:
  level:
    root: INFO
    com.solacesystems.jcsmp: INFO
    org.springframework: INFO