spring:
  cloud:
    stream:
      bindings:
        input:
          destination: TWEETS.Q
          binder: local_solace
          group: YELLING
        output:
          destination: tweets/stream/nofeatures/noyelling
          binder: localsolace
      binders:
        localsolace:
          type: solace
          environment:
            spring:
              solace:
                host: tcp://localhost:55555
                msgVpn: default
                clientUsername: default
                clientPassword: default
                connectRetries: 1
                reconnectRetries: -1
                # Add API properties here
                apiProperties: 
                  generate_sequence_numbers: true 
                  generate_sender_id: true 
                  generate_send_timestamps: true
      solace:
        bindings:
          input:
            consumer:
              queueAdditionalSubscriptions: tweets/stream/nofeatures

logging:
  level:
    root: INFO
    com.solacesystems.jcsmp: INFO
    org.springframework: INFO
    
server:
  port: 8092

